导入numpy模块

In [1]:
import numpy as np

In [2]:
array = [1,2,3,4,5]
array += 1

TypeError: 'int' object is not iterable

numpy的类型ndarray

In [3]:
array1 = np.array([1,2,3,4,5])
print (type(array1))

<class 'numpy.ndarray'>


In [4]:
array2 = array1 + 1
array2

array([2, 3, 4, 5, 6])

In [5]:
array2 + array1

array([ 3,  5,  7,  9, 11])

In [6]:
array2 * array1

array([ 2,  6, 12, 20, 30])

索引

In [7]:
array1[0]

1

In [8]:
array1[3]

4

In [9]:
array[:3]

[1, 2, 3]

In [10]:
array1

array([1, 2, 3, 4, 5])

一维数组

In [11]:
array1.shape

(5,)

In [12]:
tang_list = [1,2,3,4,5]
tang_list.shape

AttributeError: 'list' object has no attribute 'shape'

二维数组

In [13]:
a = np.array([[1,2,3],[4,5,6]])

In [14]:
a.shape

(2, 3)