## Numpy练习题

打印当前Numpy版本

In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.15.1


构造一个全零的矩阵，并打印其占用的内存大小

In [3]:
z = np.zeros((5,5))
print ('%d bytes'%(z.size * z.itemsize))

200 bytes


打印一个函数的帮助文档，比如numpy.add

In [4]:
print (help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

创建一个10-49的数组，并将其倒序排列

In [5]:
new_array = np.arange(10,50,1)
new_array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

找到一个数组中不为0的索引,很常用,在opencv中也有相似的api

In [6]:
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10], dtype=int64),)

随机构造一个3*3矩阵，并打印其中最大与最小值

In [7]:
new_array = np.random.random((3,3))
new_array.min()

0.007425469899815518

In [8]:
new_array.max()

0.8606754395975713

构造一个5*5的矩阵，令其值都为1，并在最外层加上一圈0

In [9]:
tang_array = np.ones((5,5))
tang_array = np.pad(tang_array,pad_width = 1,mode = 'constant',constant_values = 0)
tang_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [10]:
#print (help(np.pad))

构建一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [11]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

对一个5*5的矩阵做归一化操作

In [12]:
new_array = np.random.random((5,5))
new_array_max = new_array.max()
new_array_min = new_array.min()
new_array = (new_array-new_array_min)/(new_array_max - new_array_min)
new_array

array([[0.01106912, 0.53040093, 0.925493  , 0.27588446, 0.86919616],
       [0.08447087, 0.80285034, 0.12148268, 0.9576137 , 0.74155689],
       [0.91301546, 0.76819096, 0.83248925, 0.        , 0.61985573],
       [0.7252474 , 0.38569775, 1.        , 0.1155848 , 0.41394663],
       [0.19235064, 0.21579164, 0.89659666, 0.93040611, 0.16945014]])

找到两个数组中相同的值

In [13]:
z1 = np.random.randint(0,10,10) 
z2 = np.random.randint(0,10,10)
print (z1)
print (z2)
print (np.intersect1d(z1,z2))

[5 9 8 9 9 8 3 9 0 8]
[3 5 8 7 5 5 6 8 8 2]
[3 5 8]


得到今天 明天 昨天的日期

In [14]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [15]:
yesterday

numpy.datetime64('2023-10-21')

In [16]:
today

numpy.datetime64('2023-10-22')

In [17]:
tommorow

numpy.datetime64('2023-10-23')

得到一个月中所有的天

In [18]:
np.arange('2023-10','2023-11',dtype='datetime64[D]')

array(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04',
       '2023-10-05', '2023-10-06', '2023-10-07', '2023-10-08',
       '2023-10-09', '2023-10-10', '2023-10-11', '2023-10-12',
       '2023-10-13', '2023-10-14', '2023-10-15', '2023-10-16',
       '2023-10-17', '2023-10-18', '2023-10-19', '2023-10-20',
       '2023-10-21', '2023-10-22', '2023-10-23', '2023-10-24',
       '2023-10-25', '2023-10-26', '2023-10-27', '2023-10-28',
       '2023-10-29', '2023-10-30', '2023-10-31'], dtype='datetime64[D]')

得到一个数的整数部分

In [19]:
z = np.random.uniform(0,10,10)
z

array([5.27233007, 2.18731392, 6.25624013, 8.56006824, 4.78429742,
       1.25837775, 2.28115729, 0.80240654, 6.47032197, 5.23265313])

In [20]:
np.floor(z)

array([5., 2., 6., 8., 4., 1., 2., 0., 6., 5.])

构造一个数组，让它不能被改变

In [21]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

打印大数据的部分值，全部值

In [22]:
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

找到在一个数组中，最接近一个数的索引

In [23]:
z = np.arange(100)
v = np.random.uniform(0,100)
print (v)
index = (np.abs(z-v)).argmin()
print (z[index])

98.40865644353408
98


32位float类型和32位int类型转换

In [24]:
z = np.arange(10,dtype=np.int32)
print (z.dtype)
z = z.astype(np.float32)
print (z.dtype)

int32
float32


打印数组元素位置坐标与数值

In [25]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print (index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


按照数组的某一列进行排序

In [26]:
z = np.random.randint(0,10,(3,3))
print (z)
print (z[z[:,1].argsort()])

[[4 6 9]
 [8 8 0]
 [2 5 7]]
[[2 5 7]
 [4 6 9]
 [8 8 0]]


统计数组中每个数值出现的次数

In [27]:
z = np.array([1,1,1,2,2,3,3,4,5,8])
np.bincount(z)

array([0, 3, 2, ..., 0, 0, 1], dtype=int64)

如何对一个四维数组的最后两维来求和

In [28]:
z = np.random.randint(0,10,(4,4,4,4))
z

array([[[[0, 8, 9, 6],
         [4, 1, 2, 3],
         [7, 5, 8, 7],
         [9, 5, 0, 6]],

        [[6, 9, 2, 8],
         [6, 3, 3, 9],
         [4, 1, 9, 8],
         [5, 0, 4, 0]],

        [[5, 7, 9, 8],
         [9, 9, 4, 8],
         [0, 8, 9, 3],
         [3, 9, 7, 5]],

        [[2, 4, 4, 8],
         [0, 1, 7, 3],
         [8, 5, 0, 5],
         [3, 1, 7, 5]]],


       [[[5, 8, 9, 6],
         [2, 1, 8, 4],
         [6, 9, 5, 4],
         [9, 1, 6, 6]],

        [[3, 5, 2, 7],
         [6, 6, 0, 6],
         [4, 8, 9, 2],
         [7, 9, 9, 3]],

        [[9, 9, 4, 5],
         [3, 4, 0, 7],
         [7, 2, 3, 6],
         [2, 7, 3, 6]],

        [[3, 7, 3, 4],
         [1, 6, 1, 4],
         [8, 2, 9, 7],
         [5, 4, 5, 9]]],


       [[[8, 9, 6, 0],
         [5, 7, 0, 5],
         [4, 5, 5, 8],
         [6, 6, 6, 5]],

        [[7, 4, 9, 5],
         [1, 2, 0, 4],
         [2, 1, 4, 9],
         [2, 7, 4, 4]],

        [[1, 9, 8, 2],
         [6, 3, 7, 2],
         [

In [29]:
res = z.sum(axis=(-2,-1))
res

array([[ 80,  77, 103,  63],
       [ 89,  86,  77,  78],
       [ 85,  65,  68,  75],
       [ 54,  75,  54,  84]])

交换矩阵中的两行

In [30]:
z = np.arange(25).reshape(5,5)
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
z[[0,1]] = z[[1,0]]
z

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

找到一个数组中最常出现的数字

In [32]:
z = np.random.randint(0,10,50)
print (np.bincount(z).argmax())

7


快速查找TOP n

In [33]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print (z[np.argpartition(-z,n)[:n]])

[9997 9998 9999 9996 9995]


去除掉一个数组中，所有元素都相同的数据

In [34]:
np.set_printoptions(threshold=np.nan)
z = np.random.randint(0,3,(10,3))
z

array([[2, 0, 1],
       [1, 2, 0],
       [2, 0, 1],
       [0, 1, 2],
       [1, 1, 0],
       [2, 2, 2],
       [1, 1, 1],
       [1, 2, 0],
       [2, 1, 2],
       [2, 2, 0]])

In [35]:
e = np.all(z[:,1:] == z[:,:-1],axis = 1)
print (e)

[False False False False False  True  True False False False]


In [36]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
np.all(a == b)

False

In [37]:
np.any(a == b)

True