In [1]:
import numpy as np

对于ndarray结构来说，里面所有的元素必须是同一类型的
如果不是的话，会自动的向下进行转换

In [2]:
new_list = [1,2,3,4,5]
new_list_to_array = np.array(new_list)
new_list_to_array

array([1, 2, 3, 4, 5])

#### ndarray基本属性操作

数据类型

In [3]:
type(new_list_to_array)

numpy.ndarray

元素的数据类型

In [4]:
new_list_to_array.dtype

dtype('int32')

每个元素的大小

In [5]:
new_list_to_array.itemsize

4

形状

In [6]:
new_list_to_array.shape

(5,)

元素的总数，即行数乘以列数，一维就是长度

In [7]:
new_list_to_array.size

5

In [8]:
np.size(new_list_to_array)

5

In [9]:
np.shape(new_list_to_array)

(5,)

获取维度

In [10]:
new_list_to_array.ndim

1

In [11]:
new_list_to_array

array([1, 2, 3, 4, 5])

In [12]:
new_list_to_array.fill(0)
new_list_to_array

array([0, 0, 0, 0, 0])

索引与切片:跟Python都是一样的 还是从0开始的

In [13]:
new_list = [1,2,3,4,5]
new_list_to_array = np.array(new_list)
new_list_to_array[0]

1

In [14]:
new_list_to_array[1:3]

array([2, 3])

In [15]:
new_list_to_array[-2:]

array([4, 5])

矩阵格式（多维的形式）

In [16]:
new_list_to_array = np.array([[1,2,3],
                              [4,5,6],
                              [7,8,9]])
new_list_to_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
new_list_to_array.shape

(3, 3)

In [18]:
new_list_to_array.size

9

In [19]:
new_list_to_array.ndim

2

In [20]:
new_list_to_array[1,1]

5

In [21]:
new_list_to_array[1,1] = 10
new_list_to_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [22]:
new_list_to_array[1]

array([ 4, 10,  6])

In [23]:
new_list_to_array[:,1]

array([ 2, 10,  8])

In [24]:
new_list_to_array[0,0:2]

array([1, 2])

In [25]:
new_list_to_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [26]:
new_list_to_array2 = new_list_to_array
new_list_to_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [27]:
new_list_to_array2[1,1] = 100
new_list_to_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [28]:
new_list_to_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [29]:
new_list_to_array2 = new_list_to_array.copy()
new_list_to_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [30]:
new_list_to_array2[1,1] = 10000
new_list_to_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [31]:
new_list_to_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [32]:
new_list_to_array = np.arange(0,100,10)
new_list_to_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
mask = np.array([0,0,0,1,1,1,0,0,1,1],dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [34]:
new_list_to_array[mask]

array([30, 40, 50, 80, 90])

In [35]:
random_array = np.random.rand(10)
random_array

array([0.11661397, 0.81389471, 0.5741959 , 0.04440279, 0.87628355,
       0.50239476, 0.10186436, 0.83861017, 0.3250092 , 0.60001277])

In [36]:
mask = random_array > 0.5
mask

array([False,  True,  True, False,  True,  True, False,  True, False,
        True])

In [37]:
new_list_to_array[mask]

array([10, 20, 40, 50, 70, 90])

In [38]:
new_list_to_array = np.array([10,20,30,40,50])
new_list_to_array > 30

array([False, False, False,  True,  True])

In [39]:
np.where(new_list_to_array > 30)

(array([3, 4], dtype=int64),)

In [40]:
new_list_to_array[np.where(new_list_to_array > 30)]

array([40, 50])

In [41]:
new_list_to_array = np.array([1,2,3,4,5],dtype=np.float32)
new_list_to_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [42]:
new_list_to_array.dtype

dtype('float32')

In [43]:
new_list_to_array.nbytes

20

In [44]:
new_list_to_array = np.array([1,10,3.5,'str'],dtype = np.object)
new_list_to_array

array([1, 10, 3.5, 'str'], dtype=object)

In [45]:
new_list_to_array * 2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [46]:
new_list_to_array = np.array([1,2,3,4,5])
np.asarray(new_list_to_array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [47]:
new_list_to_array

array([1, 2, 3, 4, 5])

In [48]:
new_list_to_array2 = np.asarray(new_list_to_array,dtype = np.float32)

In [49]:
new_list_to_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [50]:
new_list_to_array

array([1, 2, 3, 4, 5])

In [51]:
new_list_to_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [52]:
new_list_to_array 

array([1, 2, 3, 4, 5])