### array数组的数值计算

In [1]:
import numpy as np

轴0和轴1

In [2]:
new_array = np.array([[1,2,3],[4,5,6]])
new_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.sum(new_array)

21

指定要进行的操作是沿着什么轴（维度）

In [4]:
np.sum(new_array,axis=0)

array([5, 7, 9])

In [5]:
new_array.ndim

2

In [6]:
np.sum(new_array,axis=1)

array([ 6, 15])

较低维度

In [7]:
np.sum(new_array,axis=-1)

array([ 6, 15])

In [8]:
new_array.sum()

21

In [9]:
new_array.sum(axis = 0)

array([5, 7, 9])

In [10]:
new_array.sum(axis = 1)

array([ 6, 15])

In [11]:
new_array.sum(axis = -1)

array([ 6, 15])

所有元素的乘积

In [12]:
new_array.prod()

720

In [13]:
new_array.prod(axis = 0)

array([ 4, 10, 18])

In [14]:
new_array.prod(axis = 1)

array([  6, 120])

In [15]:
new_array.min()

1

In [16]:
new_array.min(axis = 0)

array([1, 2, 3])

In [17]:
new_array.min(axis = 1)

array([1, 4])

In [18]:
new_array.max()

6

找到索引位置

In [19]:
new_array.argmin()

0

In [20]:
new_array.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [21]:
new_array.argmin(axis=1)

array([0, 0], dtype=int64)

In [22]:
new_array.argmax()

5

In [23]:
new_array.mean()

3.5

In [24]:
new_array.mean(axis = 0)

array([2.5, 3.5, 4.5])

标准差

In [25]:
new_array.std()

1.707825127659933

In [26]:
new_array.std(axis = 1)

array([0.81649658, 0.81649658])

方差的计算

In [27]:
new_array.var()

2.9166666666666665

In [28]:
new_array

array([[1, 2, 3],
       [4, 5, 6]])

clip(2,4):

element=2 if element < 2

element=4 if element > 4 

In [29]:
new_array.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [30]:
new_array = np.array([1.2,3.56,6.41])

In [31]:
new_array.round()

array([1., 4., 6.])

In [32]:
new_array.round(decimals=2)

array([1.2 , 3.56, 6.41])