In [1]:
import numpy as np

In [2]:
new_array = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
new_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [3]:
np.sort(new_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

指定维度

In [4]:
np.sort(new_array,axis = 0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [5]:
new_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

原始数组中元素的索引

In [6]:
np.argsort(new_array)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [7]:
new_array = np.linspace(0,10,10)
new_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [8]:
values = np.array([2.5,6.5,9.5])

返回一个索引数组，其中包含每个值在 new_array 中的插入位置

In [9]:
np.searchsorted(new_array,values)

array([3, 6, 9], dtype=int64)

In [10]:
new_array = np.array([[1,0,6],
                      [1,7,0],
                      [2,3,1],
                      [2,4,0]])
new_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

降序排序

In [11]:
index = np.lexsort([-1*new_array[:,0],new_array[:,2]])
index

array([3, 1, 2, 0], dtype=int64)

In [12]:
new_array = new_array[index]
new_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])