### 数组形状操作

In [1]:
import numpy as np

In [2]:
new_array = np.arange(10)
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
new_array.shape

(10,)

In [4]:
new_array.shape = 2,5
new_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
new_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小必须不能改变，其数量上就不匹配

In [6]:
new_array.shape = 3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [7]:
new_array = np.arange(10)
new_array.shape

(10,)

添加一个轴

In [8]:
new_array = new_array[np.newaxis,:]
new_array.shape

(1, 10)

In [9]:
new_array = np.arange(10)
new_array.shape

(10,)

In [10]:
new_array = new_array[:,np.newaxis]
new_array.shape

(10, 1)

In [11]:
new_array = new_array[:,np.newaxis,np.newaxis]
new_array.shape

(10, 1, 1, 1)

In [12]:
new_array = new_array.squeeze()
new_array.shape

(10,)

In [13]:
new_array.shape = 2,5

In [14]:
new_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

转置

In [15]:
new_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [16]:
new_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [17]:
new_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组的连接

In [18]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [19]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

指定的轴连接在一起，默认为0

In [20]:
c = np.concatenate((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [21]:
c = np.concatenate((a,b),axis = 0)
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [22]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [23]:
c.shape

(2, 6)

垂直堆叠

In [24]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

水平堆叠

In [25]:
np.hstack((a,b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [26]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

平铺（展直）

In [27]:
a.flatten()

array([ 123,  456,  678, 3214,  456,  134])

In [28]:
a


array([[ 123,  456,  678],
       [3214,  456,  134]])

In [29]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])