In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

构造出来一个数组

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.arange(2,20,2,dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [6]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

默认是10为底的

In [7]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [8]:
x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [9]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

坐标点网格，在向量的计算中很有用

In [10]:
x, y= np.meshgrid(x,y)

In [11]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [12]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

创建沿指定轴连接多个序列或数组

In [13]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

连接多个一维数组沿着列方向创建一个二维数组

In [14]:
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

更常用的 zeros ones，在图像中它们生成的就是黑色背景和白色背景

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((3,3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [19]:
np.ones((3,3),dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
a = np.empty(6)
a 

array([0., 0., 0., 0., 0., 0.])

In [21]:
a.shape

(6,)

In [22]:
a.fill(1)
a

array([1., 1., 1., 1., 1., 1.])

In [23]:
new_array = np.array([1,2,3,4])
new_array

array([1, 2, 3, 4])

In [24]:
np.zeros_like(new_array)

array([0, 0, 0, 0])

In [25]:
np.ones_like(new_array)

array([1, 1, 1, 1])

单位矩阵

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

对角矩阵

In [27]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])