In [1]:
import numpy as np

In [2]:
x = np.array([5,5])
y = np.array([2,2])
x,y

(array([5, 5]), array([2, 2]))

相应位置的元素相乘

In [3]:
np.multiply(x,y)

array([10, 10])

点乘

In [4]:
np.dot(x,y)

20

In [5]:
x.shape

(2,)

In [6]:
y.shape

(2,)

In [7]:
x.shape = 2,1

In [8]:
x

array([[5],
       [5]])

In [9]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [10]:
y.shape = 1,2
y

array([[2, 2]])

In [11]:
x

array([[5],
       [5]])

In [12]:
print (x.shape)
print (y.shape)

(2, 1)
(1, 2)


广播机制

In [13]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [14]:
np.dot(y,x)

array([[20]])

In [15]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print (x * y)

[[1 2 3]
 [4 5 6]]


In [16]:
y = np.array([1,1,1,4])
x = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

In [17]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

In [18]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [19]:
np.logical_not(x,y)

array([0, 0, 0, 0])