### Numpy的随机模块

0到1的范围

In [1]:
import numpy as np
np.random.rand(3,2)

array([[0.782478  , 0.3993979 ],
       [0.60844796, 0.79876354],
       [0.81766512, 0.04822193]])

随机的整数，左闭右开 -> [ )

In [2]:
np.random.randint(10,size = (5,4))

array([[0, 7, 7, 1],
       [3, 1, 5, 3],
       [0, 7, 2, 0],
       [9, 7, 3, 9],
       [6, 8, 7, 0]])

In [3]:
np.random.rand()

0.9779204645552413

In [4]:
np.random.random_sample()

0.3985976948279115

In [5]:
np.random.randint(0,10,3)

array([7, 0, 8])

均值方差归一化

In [6]:
mean, sigma = 0,0.1
np.random.normal(mean,sigma,10)

array([-0.0624651 ,  0.09830278,  0.04915398,  0.26218572, -0.19938206,
        0.07511375, -0.00032012, -0.14696069, -0.05422028, -0.1017018 ])

In [7]:
np.set_printoptions(precision = 2)  # 浮点数的小数部分将被截断为两位小数

In [8]:
mean, sigma = 0,0.1
np.random.normal(mean,sigma,10)

array([ 0.01,  0.02,  0.26,  0.01, -0.  ,  0.08,  0.03, -0.02,  0.07,
       -0.07])

### 打乱

In [9]:
new_array = np.arange(10)
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(new_array)

In [11]:
new_array

array([4, 2, 8, 0, 5, 9, 7, 3, 6, 1])

### 随机的种子

In [12]:
np.random.seed(100)

In [13]:
mean, sigma = 0,0.1
np.random.normal(mean,sigma,10)

array([-0.17,  0.03,  0.12, -0.03,  0.1 ,  0.05,  0.02, -0.11, -0.02,
        0.03])