In [1]:
import numpy as np

### 使用Numpy读写数据

In [2]:
%%writefile test.txt
1 2 3 4 5 6
2 3 5 8 7 9

Overwriting test.txt


In [3]:
data = []
with open('test.txt') as f:
    for line in f.readlines():
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [4]:
data = np.loadtxt('test.txt')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [5]:
data[:,1]

array([2., 3.])

In [6]:
%%writefile test2.txt
1,2,3,4,5,6
2,3,5,8,7,9


Overwriting test2.txt


In [7]:
data = np.loadtxt('test2.txt',delimiter = ',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [8]:
%%writefile test2.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,5,8,7,9

Overwriting test2.txt


In [9]:
data = np.loadtxt('test2.txt',delimiter = ',',skiprows = 1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

* test2.txt:路径最好放到和代码同一级别
* skiprows : 去掉几行
* delimiter = ',' :分隔符
* usecols = (0,1,4) ：指定使用哪几列

In [10]:
new_array = np.array([[1,2,3],[4,5,6]])

In [11]:
np.savetxt('test3.txt',new_array)

In [12]:
np.savetxt('test3.txt',new_array,fmt='%d')

In [13]:
np.savetxt('test3.txt',new_array,fmt='%d',delimiter = ',')

In [14]:
np.savetxt('test3.txt',new_array,fmt='%.2f',delimiter = ',')

### 读写array结构

In [15]:
new_array = np.array([[1,2,3],[4,5,6]])
np.save('new_array.npy',new_array)

In [16]:
_new = np.load('new_array.npy')
_new

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
new_array2 = np.arange(10)
new_array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.savez('test.npz', a=new_array.astype(np.uint8), b=new_array2.astype(np.uint8))

In [19]:
data = np.load('test.npz')

In [20]:
data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x000002568AE1C358>)

In [21]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [22]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)